### ISSUE TITLE
tree shaking not working with your tailwind example

### ISSUE THREAD

**Issue by Jared-Dahlke** [egoist/tsup#1005]
I copied your tailwind [example](https://github.com/egoist/tsup/issues/883#issuecomment-1726859223) you just made and added react: 
https://github.com/Jared-Dahlke/tsup-shadcn

the tailwind works now which is great! But now tree shaking is not working. In my example i am expecting Button to be about 10kb and Accordion to add more weight once it's imported. But it looks like the import size is including everything even if you only import Button.

import { Button } from "tsup-tailwind-react-shadcn"; should only be about 10kb

Any idea what I am doing wrong?

**Comment by ocavue** [comment]
I'm not seeing React in [Jared-Dahlke/tsup-shadcn](https://github.com/Jared-Dahlke/tsup-shadcn). Did you forget pushing your code?

**Comment by Jared-Dahlke** [comment]
It still works as is without react. Everything works but tree shaking

**Comment by Jared-Dahlke** [comment]
@ocavue my bad, you were right i forgot to push. It is now pushed. Do you mind trying it out please? Thank you!

**Comment by ocavue** [comment]
Your repo cannot be built because you missed the `react` in the `dependencies` field of `package.json`. 

I added `react` in `package.json` and ran the build script, the output file `dist/index.mjs` and `dist/index.js` look good to me. `dist/index.mjs` has 94 lines, and `dist/index.js` has 118 lines. I don't understand "tree shaking is not working" and I also don't know how you get the conclusion of "the import size is including everything". 

Anyway, don't see any issue on the tsup side. Going to close this issue for now.

**Comment by Jared-Dahlke** [comment]
@ocavue when i import the Button in it's using the entire lucide-react icon library.

![image](https://github.com/egoist/tsup/assets/32936978/cbd50c8b-9e51-4c98-9985-0c74a1095b04)

here are the details from that screenshot:
Input | Files | Size | Percent
-- | -- | -- | --
<bundle>.js |   | 437.77KB | 100%
↪ lucide-react | dist/cjs/lucide-react.js | 387.72KB | 88.6%
↪ tailwind-merge | dist/tailwind-merge.cjs.production.min.js (21.16KB), dist/index.js (50B) | 21.21KB | 4.8%
↪ react | cjs/react.production.min.js (6.38KB), cjs/react-jsx-runtime.production.min.js (612B), index.js (50B), jsx-runtime.js (50B) | 7.08KB | 1.6%
↪ @radix-ui/react-accordion | dist/index.js | 4.96KB | 1.1%
↪ @radix-ui/react-collapsible | dist/index.js | 2.62KB | 0.6%


Weird
