### ISSUE TITLE
Custom tsconfig path

### ISSUE THREAD

**Issue by olavoasantos** [egoist/tsup#430]
## Summary

It's a common approach to have multiple `tsconfig.json` files (e.g. `tsconfig.build.json`, `tsconfig.types.json`, `tsconfig.test.json`, etc) to configure different commands of the TypeScript code base. Currently, tsup's config option does't accept a custom path for this file, but this option is available on the ESBuild options.

## Expected behaviour

Expose the `tsconfig` option on tsup's `Options` object.

### Type

```typescript
declare type Options = {
  // ...
  tsconfig?: string;
};
```

### Usage

```typescript
import { build } from 'tsup';

build({
  // ...
  tsconfig: 'path/to/tsconfig.build.json',
}),
```

## Reference

- [ESBuild definition](https://esbuild.github.io/api/#tsconfig)

**Comment by guilhermetod** [comment]
Hey, I ran in the same issue and realized `tsup` respects `ESBuild` config, so all you gotta do is add this to `tsup.config.js`:

```js
  esbuildOptions(options) {
    Object.assign(options, {
      tsconfig: 'path/to/tsconfig.build.json',
    });
  },
```

**Comment by egoist** [comment]
@guilhermetod that line is correct but now `esbuildOptions: undefined` should also be added there.

https://github.com/egoist/tsup/blob/dbf71ae5ca1717a0e9072f58e48397a5a4dea320/src/rollup.ts#L72 this should be updated for the dts generation (which uses rollup instead of esbuild) to pick up the tsconfig you specified.

**Comment by guilhermetod** [comment]
Nice, I managed to get it partially working here, just two things I'd like to clear with you:

1. I thinks it's clearer to have a top level `tsconfig` property, otherwise we'll have to assign a global variable that will only resolve after `esbuildOptions` is called
2. Currently, the tsconfig file properties won't resolve correctly when the file makes use of `extends`. So given that I have path aliases defined in `tsconfig.base.json` and I use `tsconfig.build.json` extending `tsconfig.base.json`, I'll get a compilation error because the `paths` properties didn't get computed by rollup, since it only reads the content of the `tsconfig.build.json` file. To fix this I think we can use typescript's native API. IIRC they do have a way of reading the config file resolved options.


Both of these issues can be easily addressed, I just wanted to validate if you are ok with these changes, so I can create a PR and then have further discussion there.

**Comment by egoist** [comment]
1. sounds great,  but for 2. typescript is an optional dependency which is only used under `--dts` flag

**Comment by egoist** [comment]
never mind , we actually only need to load tsconfig for `--dts` flag. so 2. looks good 👌

**Comment by egoist** [comment]
Added in v5.8.0
