### ISSUE TITLE
Tree Shaking is not working 

### ISSUE THREAD

**Issue by shubham-kaushal** [egoist/tsup#755]
Hi @egoist,

I've recently migrated to `tsup` for our open-source projects --- [TastyCSS](https://github.com/outpostHQ/tasty) and [Jenga UI](https://github.com/outpostHQ/jengaui). I've tried to configure it as the doc suggested but still, Tree Shaking is not working, and as result packages are heavy in size.

Could you please guide me on solving the issue of Tree Shaking and reducing the package's bundle size? 🙏

**Comment by RIP21** [comment]
@shubham-kaushal how did you manage to fix that for JengaUI?

I have a monorepo and I've built a `ui-kit` that is used by a typical Vite react app.
I see that the output of `tsup` is a JS file in ESM format and that all exports are named (I have a barrel `*` export).
Plus, the package is a native ESM module and I don't output CJS only ESM. `sideEffects` are also `false` in the `package.json` 

So, something like that:
```
  "sideEffects": [
    "**/*.css"
  ],
  "types": "./dist/index.d.ts",
  "source": "./src/index.ts",
  "module": "./dist/index.js",
  "exports": {
    ".": "./dist/index.js",
    "./src/shared-globals.css": "./src/shared-globals.css"
  },
  ```

Then, even tho I import only one component, which should be around 9kb, it imports the entire thing making it 65kb.
The same happens if I use[`size-limit` package](https://github.com/ai/size-limit?tab=readme-ov-file#big-libraries) which uses Webpack to check the library size.

Should I make every single component a package with `package.json` or what?
