### ISSUE TITLE
Ignore es5 target in esm format

### ISSUE THREAD

**Issue by egoist** [egoist/tsup#82]
Because esm isn't supported in es5 environment anyways, we should change it to something like `es2018` instead.

**Comment by egoist** [comment]
btw buble is somewhat buggy, I think I'll remove that in the next version and maybe replace it with SWC?

**Comment by egoist** [comment]
it's now replaced by swc in 5.11.0

**Comment by DerGernTod** [comment]
i know this is closed for half a year, but i just started using tsup and i'm running into a problem with this.

i'm currently working on transforming a larger project into a monorepo. one of the packages is a shared package for multiple others, which i use tsup to bundle for the others. now, i prefer to use esm since it's easier to work with typescript and when bundling, the paths don't resolve weirdly and can easily be tree-shaked. now, my ts target is es5. and here's the problem with that:

since tsup doesn't seem to transpile down to es5 for esm, i can't bundle my tsup shared package into an es5 compatible bundle. ts doesn't transpile node_modules (obviously), and esbuild (which i use to bundle the target package) doesn't transpile into es5. this results in

`Transforming const to the configured target environment ("es5") is not supported yet`

so my only solution now is to go with commonjs for the shared bundle, which blocks treeshaking somewhat and screws up my final bundle.

is there any workaround i can implement to make tsup transpile to es5 even in esm mode? in ts, you have two compiler configs exactly for that reason: "module" and "target" which both have a different meaning.
