### ISSUE TITLE
tsup-node doesn't exclude all packages

### ISSUE THREAD

**Issue by zfben** [egoist/tsup#850]
Reproduction steps:

1. `git clone git@github.com:faasjs/faasjs.git`
2. `npm install`
3. `npm build -w packages/knex`
4. packages/knex/dist/index.mjs is correct.
5. change root's package.json's tsup version to `6.6.3`
6. `npm install`
7. `npm build -w packages/knex`
8. tsup bundled @faasjs/logger

I expect tsup-node to exclude @faasjs/logger too, such as tsup's 5.x verion.

Is this a bug or something I missed?

**Comment by hyrious** [comment]
This is because your top-level tsconfig.json has `paths`: `"@faasjs/*": ["./packages/*/src"]`, this config changes the import to relative path so the tsup-node will treat it as bundled in. [relative code here](https://github.com/egoist/tsup/blob/97f3abf74c051ca7ce7915c5bb2573ae54bff7b1/src/esbuild/external.ts#L27-L30)

**Comment by zfben** [comment]
> This is because your top-level tsconfig.json has `paths`: `"@faasjs/*": ["./packages/*/src"]`, this config changes the import to relative path so the tsup-node will treat it as bundled in. [relative code here](https://github.com/egoist/tsup/blob/97f3abf74c051ca7ce7915c5bb2573ae54bff7b1/src/esbuild/external.ts#L27-L30)

Thank you, I changed it to packages/* then it works!
