### ISSUE TITLE
Sourcemaps break when using `treeshake: 'smallest'`

### ISSUE THREAD

**Issue by aleclarson** [egoist/tsup#889]
It seems when Rollup is used for extra tree-shaking, the sourcemaps no longer trace back to correct positions in the source code. This makes breakpoints effectively useless.

You might be forgetting to feed the sourcemaps into Rollup?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/889">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/889/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/889/pledge.svg">
</picture>
</a>

**Comment by xia0hj** [comment]
I met this problem too, it might be caused by incorrect use of `applySourceMap` here
https://github.com/egoist/tsup/blob/322cb772d8ddb73fbb6192199c29c3917c659ce0/src/plugin.ts#L156-L166

correct example: https://github.com/mozilla/source-map/blob/master/test/test-source-map-generator.js#L356-L362

Besides, default output is `./dist/index.js.map`. But rollup treeshake sourcemap path is `./out.js.map`, result in incorrect sources path `src/index.ts`. The correct one should be `../src/index.ts`

I fixed these 2 bugs in https://github.com/egoist/tsup/pull/1069

**Comment by aleclarson** [comment]
In addition to @xia0hj's PR, there's also this one: https://github.com/egoist/tsup/pull/949

I've not tested it myself. Interestingly, it's quite a bit different than @xia0hj's solution.
